#!/bin/bash
# Regenerates photos/manifest.js from the image files in photos/.
# Run this any time photos are added or removed so the carousel stays in sync.
set -e
cd "$(dirname "$0")/photos"

files=$(find . -maxdepth 1 -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) ! -iname 'hero.*' -print | sed 's|^\./||' | sort)

{
  echo "// Auto-generated by update-photos.sh — run that script after adding or removing photos."
  echo "window.PHOTO_MANIFEST = ["
  if [ -n "$files" ]; then
    echo "$files" | sed 's/.*/  "&",/' | sed '$ s/,$//'
  fi
  echo "];"
} > manifest.js

echo "Wrote photos/manifest.js with $(printf '%s\n' "$files" | grep -c .) photo(s)"
